# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
language: python
sudo: false
python:
  - 3.6
install:
  - pip install docopt
  - pip install future
  - pip install psutil
script:
  - oracle-java8-set-default
  - python main.py doctor --verbose
  - oracle-java9-set-default
  - python main.py doctor --verbose
