# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
language: python
sudo: false
python:
  - 3.6
install:
  - pip install docopt
  - pip install future
  - pip install psutil
script:
  - jdk_switcher use oraclejdk8
  - python main.py doctor
  - jdk_switcher use oraclejdk9
  - python main.py doctor
