# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
language: python
sudo: required
python:
  - 3.6
install:
  - pip install docopt
  - pip install future
  - pip install psutil
jdk:
  - oraclejdk8
  - oraclejdk9
matrix:
  include:
    - script:
        - jdk_switcher use oraclejdk8
        - python main.py doctor --verbose
    - script:
        - jdk_switcher use oraclejdk9
        - bash ./test_doctor_failure.sh
