# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build-jdk8:
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/android:api-28-alpha
        environment:
          JVM_OPTS: -Xmx3200m
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.0

    working_directory: ~/android-sdk-enhanced-code-checkout-directory

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-28
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Python dependencies
          command: |
            sudo apt-get install python3 python3-pip python3-venv
            # Setup python3
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-28

      - run:
          name: Run JDK8 tests
          command: |
            # Any failure is a failure
            set -e
            python3 -m venv venv
            . venv/bin/activate
            # Verify doctor succeeds
            python3 src/main.py doctor --verbose
            python3 src/main.py list api versions --arm
            python3 src/main.py list build tools
            python3 src/main.py list installed packages
            python3 src/main.py install version 4
            python3 src/main.py install version 14 --arm
            python3 src/main.py install version 24 --x86
            python3 src/main.py list others
            python3 src/main.py update all --verbose

  build-jdk9:
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/openjdk:10-jdk
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.0

    working_directory: ~/android-sdk-enhanced-code-checkout-directory

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-28
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Python dependencies
          command: |
            sudo apt-get install python3 python3-pip python3-venv
            # Setup python3
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-28

      - run:
          name: Run JDK9 tests
          command: |
            # Any failure is a failure
            set -e
            python3 -m venv venv
            . venv/bin/activate
            # The only thing we want to test with JDK9 is the doctor returns failure
            if python src/main.py doctor --verbose; then
              exit 1  # This command should have failed
            else
              exit 0  # This command failure is expected
            fi


# https://discuss.circleci.com/t/how-to-test-multiple-versions-by-triggering-jobs-with-a-shell-function/11305
workflows:
  version: 2
  build:
    jobs:
      - build-jdk8
      - build-jdk9
