# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/android:api-28-alpha
        environment:
          JVM_OPTS: -Xmx3200m
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.0
      

    working_directory: ~/android-sdk-enhanced-code-checkout-directory

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-28
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install Python dependencies
          command: |
            sudo apt-get install python3 python3-pip python3-venv
            # Setup python3
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-28

      - run:
          name: Python 3 tests
          command: |
            # Any failure is a failure
            set -e
            python3 -m venv venv
            . venv/bin/activate
            bash ./tests/test_doctor.sh